# Generated by Django 3.2.4 on 2021-06-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produk Karpet', 'verbose_name_plural': 'Produk Karpet Mantab'},
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Judul'),
        ),
    ]
